"""Rastro conversacional de un comando local.

El canónico no tiene canal de captura de comandos: el rastro de un comando local
SON mensajes de la conversación (`utils/messages.ts:566-601`,
`processSlashCommand.tsx:679-704`), y por eso sobrevive al `.jsonl` y sigue
visible para el modelo en turnos posteriores.
"""

from __future__ import annotations

from typing import Any

COMMAND_NAME_TAG = "command-name"
COMMAND_MESSAGE_TAG = "command-message"
COMMAND_ARGS_TAG = "command-args"
LOCAL_COMMAND_STDOUT_TAG = "local-command-stdout"
LOCAL_COMMAND_STDERR_TAG = "local-command-stderr"
LOCAL_COMMAND_CAVEAT_TAG = "local-command-caveat"

LOCAL_COMMAND_CAVEAT_TEXT = (
    "Caveat: The messages below were generated by the user while running local "
    "commands. DO NOT respond to these messages or otherwise consider them in "
    "your response unless the user explicitly asks you to."
)

LOCAL_COMMAND_META_KEY = "is_meta"


def format_command_input_tags(command_name: str, args: str) -> str:
    return (
        f"<{COMMAND_NAME_TAG}>/{command_name}</{COMMAND_NAME_TAG}>\n"
        f"<{COMMAND_MESSAGE_TAG}>{command_name}</{COMMAND_MESSAGE_TAG}>\n"
        f"<{COMMAND_ARGS_TAG}>{args}</{COMMAND_ARGS_TAG}>"
    )


def create_synthetic_user_caveat_message() -> dict[str, Any]:
    return {
        "role": "user",
        "content": f"<{LOCAL_COMMAND_CAVEAT_TAG}>{LOCAL_COMMAND_CAVEAT_TEXT}"
        f"</{LOCAL_COMMAND_CAVEAT_TAG}>",
        LOCAL_COMMAND_META_KEY: True,
    }


def create_command_input_message(command_name: str, args: str = "") -> dict[str, Any]:
    return {"role": "user", "content": format_command_input_tags(command_name, args)}


def create_local_command_stdout_message(text: str) -> dict[str, Any]:
    return {
        "role": "user",
        "content": f"<{LOCAL_COMMAND_STDOUT_TAG}>{text}</{LOCAL_COMMAND_STDOUT_TAG}>",
    }


def create_local_command_stderr_message(text: str) -> dict[str, Any]:
    return {
        "role": "user",
        "content": f"<{LOCAL_COMMAND_STDERR_TAG}>{text}</{LOCAL_COMMAND_STDERR_TAG}>",
    }


def create_local_command_messages(
    command_name: str,
    args: str = "",
    *,
    stdout: str | None = None,
    stderr: str | None = None,
) -> list[dict[str, Any]]:
    messages = [
        create_synthetic_user_caveat_message(),
        create_command_input_message(command_name, args),
    ]
    if stdout:
        messages.append(create_local_command_stdout_message(stdout))
    if stderr:
        messages.append(create_local_command_stderr_message(stderr))
    return messages


def is_local_command_output_message(message: Any) -> bool:
    if not isinstance(message, dict) or message.get("role") != "user":
        return False
    content = message.get("content")
    if not isinstance(content, str):
        return False
    return any(
        f"<{tag}>" in content
        for tag in (LOCAL_COMMAND_STDOUT_TAG, LOCAL_COMMAND_STDERR_TAG)
    )


__all__ = [
    "COMMAND_ARGS_TAG",
    "COMMAND_MESSAGE_TAG",
    "COMMAND_NAME_TAG",
    "LOCAL_COMMAND_CAVEAT_TAG",
    "LOCAL_COMMAND_CAVEAT_TEXT",
    "LOCAL_COMMAND_META_KEY",
    "LOCAL_COMMAND_STDERR_TAG",
    "LOCAL_COMMAND_STDOUT_TAG",
    "create_command_input_message",
    "create_local_command_messages",
    "create_local_command_stderr_message",
    "create_local_command_stdout_message",
    "create_synthetic_user_caveat_message",
    "format_command_input_tags",
    "is_local_command_output_message",
]
