from enum import Enum
from typing import Optional, Protocol


class AgentMode(str, Enum):
    FOREGROUND = "foreground"
    BACKGROUND = "background"
    FORK = "fork"


class ModeManagerProtocol(Protocol):
    def register(self, *, task_id: str, mode: AgentMode) -> None: ...
    def unregister(self, task_id: str) -> None: ...
    def get_mode(self, task_id: str) -> Optional[AgentMode]: ...
    def set_mode(self, task_id: str, mode: AgentMode) -> None: ...
    def on_complete(self, task_id: str) -> bool: ...
